Implement `strict` input

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -48,9 +48,23 @@ jobs:
     - uses: actions/checkout@v2
     - uses: mondeja/strip-gh-theme-links@master
       with:
-        files: |
-          README.md
+        files: README.md
+        strict: true
     - run: cat README.md
+    - name: Strict integration test
+      uses: mondeja/strip-gh-theme-links@master
+      with:
+        files: |
+          unexistent-file.md
+          another-unexistent-file.md
+        strict: true
+    - if: ${{ success() }}
+      run: |
+        echo "Strict integration test failed"
+        exit 1
+    - if: ${{ failure() }}
+      run: echo "Strict integration test success"
+
 
   npm:
     if: startsWith(github.ref, 'refs/tags/')
